In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/E-Commerce - E-Commerce (1).csv")

In [ ]:
df.head()

   Order_ID Product_Name     Category  Price  Quantity Customer_ID  Order_Date
0         1       Laptop  Electronics   1200         2        C101  01-01-2024
1         2   Headphones  Electronics     80         3        C102  02-01-2024
2         3        Chair    Furniture    150         1        C103  03-01-2024
3         4   Smartphone  Electronics    600         1        C104  04-01-2024
4         5         Desk    Furniture    200         2        C105  05-01-2024

In [ ]:
df.tail()

,Order_ID,Product_Name,Category,Price,Quantity,Customer_ID,Order_Date
25,26,Watch,Accessories,120,1,C108,26-01-2024
26,27,Camera,Electronics,750,1,C113,27-01-2024
27,28,Jeans,Apparel,35,4,C113,28-01-2024
28,29,Printer,Electronics,130,1,C105,29-01-2024
29,30,Perfume,Beauty,30,3,C102,30-01-2024

In [ ]:
df.shape

(30, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      30 non-null     int64
 1   Product_Name  30 non-null     object
 2   Category      30 non-null     object
 3   Price         30 non-null     int64
 4   Quantity      30 non-null     int64
 5   Customer_ID   30 non-null     object
 6   Order_Date    30 non-null     object
dtypes: int64(3), object(4)
memory usage: 1.8+ KB

In [ ]:
df.describe()

        Order_ID        Price   Quantity
count  30.000000    30.000000  30.000000
mean   15.500000   200.833333   2.033333
std     8.803408   277.134610   1.159171
min     1.000000    15.000000   1.000000
25%     8.250000    41.250000   1.000000
50%    15.500000   110.000000   2.000000
75%    22.750000   195.000000   3.000000
max    30.000000  1200.000000   5.000000

In [ ]:
col=df.columns
col

Index(['Order_ID', 'Product_Name', 'Category', 'Price', 'Quantity',
       'Customer_ID', 'Order_Date'],
      dtype='object')

In [ ]:
df.isnull().sum()

Order_ID        0
Product_Name    0
Category        0
Price           0
Quantity        0
Customer_ID     0
Order_Date      0
dtype: int64

In [ ]:
df['Category'].unique()

array(['Electronics', 'Furniture', 'Apparel', 'Books', 'Accessories',
       'Beauty'], dtype=object)

In [ ]:
df['Category'].nunique()

6

In [ ]:
df['Quantity'].sum()

np.int64(61)

In [ ]:
df.groupby('Category')['Price'].mean().sort_values()

Category
Books           17.500000
Beauty          27.500000
Apparel         37.500000
Accessories     82.500000
Furniture      196.666667
Electronics    420.000000
Name: Price, dtype: float64

In [ ]:
df['Product_Price']=df['Price']/df['Quantity']

In [ ]:
df.head()

,Order_ID,Product_Name,Category,Price,Quantity,Customer_ID,Order_Date,Product_Price
0,1,Laptop,Electronics,1200,2,C101,01-01-2024,600.000000
1,2,Headphones,Electronics,80,3,C102,02-01-2024,26.666667
2,3,Chair,Furniture,150,1,C103,03-01-2024,150.000000
3,4,Smartphone,Electronics,600,1,C104,04-01-2024,600.000000
4,5,Desk,Furniture,200,2,C105,05-01-2024,100.000000

In [ ]:
df1=df[df['Product_Price']==df['Product_Price'].max()]
df1

,Order_ID,Product_Name,Category,Price,Quantity,Customer_ID,Order_Date,Product_Price
12,13,Camera,Electronics,800,1,C113,13-01-2024,800.0

In [ ]:
df.iloc[[df['Price'].idxmax()]]

,Order_ID,Product_Name,Category,Price,Quantity,Customer_ID,Order_Date,Product_Price
0,1,Laptop,Electronics,1200,2,C101,01-01-2024,600.0

In [ ]:
df['Total']=df['Price']*df['Quantity']
max_total_customer_id = df.groupby('Customer_ID')['Total'].sum().idxmax()
df[df['Customer_ID'] == max_total_customer_id]

,Order_ID,Product_Name,Category,Price,Quantity,Customer_ID,Order_Date,Product_Price,Total
0,1,Laptop,Electronics,1200,2,C101,01-01-2024,600.000000,2400
15,16,Perfume,Beauty,25,4,C101,16-01-2024,6.250000,100
19,20,Headphones,Electronics,70,3,C101,20-01-2024,23.333333,210

In [ ]:
df['Total'].sum()

np.int64(8615)

In [ ]:
df[df['Order_Date']=='05-01-2024']

,Order_ID,Product_Name,Category,Price,Quantity,Customer_ID,Order_Date,Product_Price,Total
4,5,Desk,Furniture,200,2,C105,05-01-2024,100.0,400

In [ ]:
df2=df.groupby('Customer_ID')['Total'].sum().sort_values(ascending=False).head(3)
df2
#Print entie detail of these 3 cusr=t in df2
for i in df2.index:
  print(df[df['Customer_ID']==i])

    Order_ID Product_Name     Category  Price  Quantity Customer_ID  \
0          1       Laptop  Electronics   1200         2        C101
15        16      Perfume       Beauty     25         4        C101
19        20   Headphones  Electronics     70         3        C101

    Order_Date  Product_Price  Total
0   01-01-2024     600.000000   2400
15  16-01-2024       6.250000    100
19  20-01-2024      23.333333    210
    Order_ID Product_Name     Category  Price  Quantity Customer_ID  \
12        13       Camera  Electronics    800         1        C113
26        27       Camera  Electronics    750         1        C113
27        28        Jeans      Apparel     35         4        C113

    Order_Date  Product_Price  Total
12  13-01-2024         800.00    800
26  27-01-2024         750.00    750
27  28-01-2024           8.75    140
   Order_ID Product_Name     Category  Price  Quantity Customer_ID  \
3         4   Smartphone  Electronics    600         1        C104

   Order_Date  Product_Price  Total
3  04-01-2024          600.0    600

In [ ]:
df.groupby('Category')['Order_ID'].unique()

Category
Accessories                        [11, 12, 18, 26]
Apparel                      [6, 8, 14, 21, 24, 28]
Beauty                                     [16, 30]
Books                                       [9, 22]
Electronics    [1, 2, 4, 7, 13, 15, 17, 20, 27, 29]
Furniture                    [3, 5, 10, 19, 23, 25]
Name: Order_ID, dtype: object

In [ ]:
df['Category'].value_counts()

Category
Electronics    10
Furniture       6
Apparel         6
Accessories     4
Books           2
Beauty          2
Name: count, dtype: int64

In [ ]:
df.sort_values(by='Category')

,Order_ID,Product_Name,Category,Price,Quantity,Customer_ID,Order_Date,Product_Price,Total
25,26,Watch,Accessories,120,1,C108,26-01-2024,120.000000,120
10,11,Watch,Accessories,100,1,C111,11-01-2024,100.000000,100
11,12,Backpack,Accessories,50,2,C112,12-01-2024,25.000000,100
17,18,Sunglasses,Accessories,60,2,C118,18-01-2024,30.000000,120
27,28,Jeans,Apparel,35,4,C113,28-01-2024,8.750000,140
23,24,Shoes,Apparel,45,2,C112,24-01-2024,22.500000,90
5,6,Shirt,Apparel,30,5,C106,06-01-2024,6.000000,150
7,8,Shoes,Apparel,50,2,C108,08-01-2024,25.000000,100
20,21,Shirt,Apparel,25,4,C110,21-01-2024,6.250000,100
13,14,Jeans,Apparel,40,3,C114,14-01-2024,13.333333,120
29,30,Perfume,Beauty,30,3,C102,30-01-2024,10.000000,90
15,16,Perfume,Beauty,25,4,C101,16-01-2024,6.250000,100
21,22,Book,Books,20,2,C105,22-01-2024,10.000000,40
8,9,Book,Books,15,3,C109,09-01-2024,5.000000,45
26,27,Camera,Electronics,750,1,C113,27-01-2024,750.000000,750
19,20,Headphones,Electronics,70,3,C101,20-01-2024,23.333333,210
0,1,Laptop,Electronics,1200,2,C101,01-01-2024,600.000000,2400
28,29,Printer,Electronics,130,1,C105,29-01-2024,130.000000,130
12,13,Camera,Electronics,800,1,C113,13-01-2024,800.000000,800
6,7,Tablet,Electronics,300,1,C107,07-01-2024,300.000000,300
3,4,Smartphone,Electronics,600,1,C104,04-01-2024,600.000000,600
1,2,Headphones,Electronics,80,3,C102,02-01-2024,26.666667,240
16,17,Speaker,Electronics,120,2,C108,17-01-2024,60.000000,240
14,15,Printer,Electronics,150,1,C115,15-01-2024,150.000000,150
18,19,Table,Furniture,250,1,C119,19-01-2024,250.000000,250
9,10,Desk,Furniture,180,1,C110,10-01-2024,180.000000,180
22,23,Chair,Furniture,180,1,C110,23-01-2024,180.000000,180
4,5,Desk,Furniture,200,2,C105,05-01-2024,100.000000,400
24,25,Desk,Furniture,220,1,C102,25-01-2024,220.000000,220
2,3,Chair,Furniture,150,1,C103,03-01-2024,150.000000,150

In [ ]:
df[df['Quantity']>3]

,Order_ID,Product_Name,Category,Price,Quantity,Customer_ID,Order_Date,Product_Price,Total
5,6,Shirt,Apparel,30,5,C106,06-01-2024,6.00,150
15,16,Perfume,Beauty,25,4,C101,16-01-2024,6.25,100
20,21,Shirt,Apparel,25,4,C110,21-01-2024,6.25,100
27,28,Jeans,Apparel,35,4,C113,28-01-2024,8.75,140

In [ ]:
df.groupby('Product_Name')['Quantity'].mean()

Product_Name
Backpack      2.000000
Book          2.500000
Camera        1.000000
Chair         1.000000
Desk          1.333333
Headphones    3.000000
Jeans         3.500000
Laptop        2.000000
Perfume       3.500000
Printer       1.000000
Shirt         4.500000
Shoes         2.000000
Smartphone    1.000000
Speaker       2.000000
Sunglasses    2.000000
Table         1.000000
Tablet        1.000000
Watch         1.000000
Name: Quantity, dtype: float64

In [ ]:
df.groupby('Product_Name')['Quantity'].sum().max()

9

In [ ]:
df['Product_Name'].value_counts()[df['Product_Name'].value_counts()>1]

Product_Name
Desk          3
Headphones    2
Printer       2
Chair         2
Shirt         2
Shoes         2
Watch         2
Book          2
Jeans         2
Camera        2
Perfume       2
Name: count, dtype: int64

In [ ]:
df.groupby(['Category','Product_Name'])["Total"].sum()   #TOTAL COST PER PRODUCT IN EACH CATEGORY

Category     Product_Name
Accessories  Backpack         100
             Sunglasses       120
             Watch            220
Apparel      Jeans            260
             Shirt            250
             Shoes            190
Beauty       Perfume          190
Books        Book              85
Electronics  Camera          1550
             Headphones       450
             Laptop          2400
             Printer          280
             Smartphone       600
             Speaker          240
             Tablet           300
Furniture    Chair            330
             Desk             800
             Table            250
Name: Total, dtype: int64

In [ ]:
df.groupby(['Category'])["Total"].sum()

Category
Accessories     440
Apparel         700
Beauty          190
Books            85
Electronics    5820
Furniture      1380
Name: Total, dtype: int64